### ISSUE TITLE
Sistem za govornu komunikaciju

### ISSUE THREAD

**Issue by tamarakatic** [ftn-ai-lab/nm-2017#11]
## Tim
**Tamara Katić E2** 96/2017
**Nemanja Milićević** E2 121/2017
**Predrag Njegovanović** E2 94/2017
**Novica Šarenac** E2 88/2017

## Tema
Sistem se sastoji iz 3 modula:
- **speech-to-text**
- **text-to-text (chatbot)**
- **text-to-speech** 

Osnovna ideja je implementacija sistema sa kojim može da se komunicira govorom.

### Speech-to-text
Modul koji prepoznaje govor, zasnovan na arhitekturi mreže predstavljene u ovom [radu](https://arxiv.org/abs/1412.5567). Za obučavanje mreže koristimo [Common Voice](https://voice.mozilla.org/data) podatke.

### Text-to-text (chatbot)
Modul koji odgovara na tekstualni izlaz iz prethodnog modula. Koristićemo LSTM, sa podacima iz [Cornell Movie Dialogs Corpus](https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html) dataset-a.

### Text-to-speech
Modul koji generiše govor na osnovu teksta, odnosno izlaza iz prethodnog modula. Koristićemo pretreniran Google-ov [WaveNet](https://deepmind.com/blog/wavenet-generative-model-raw-audio/).

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Dosta veliki i ambiciozan projekat, ali vredi probati da vidimo šta ćete sve uspeti od stvari koje ste zamislili.
