### ISSUE TITLE
Predikcija cena kriptovaluta 

### ISSUE THREAD

**Issue by Milica95** [ftn-ai-lab/nm-2017#13]
**Tim**

Milica Milutinovic E2 27-2017
Dejan Kuzmanovic E2 22-2017

**Tema**

Cilj nam je da predvidimo cenu 4 popularne kriptovalute (Bitcoin, Litecoin, Ethereum, Ripple). Kao ulazne podatke planiramo da koristimo informacije o samom trzistu koje su dostupne na internetu kao na primer: 
oznaka_valute
cena_usd
24h_obim_prodaje_usd
24h_obim_prodaje_valute
trzisna_kapitulizacija
volatilnost_valute
Pored ovih podataka koristićemo i podatke o samom blockchainu (block size, cost per transaction, difficulty, hash rate, transactions per block, itd). 
Takodje, radicemo analizu sentimenta Twitter statusa o ovim valutama, a ti podaci ce nam biti jedan od ulaza u nas model. 

Za model ćemo koristiti LSTM mrežu sa sequence2sequence arhitekturom. Pored ovoga ćemo probati i klasičnu time-series forecast metodu i uporediti rezultate. 

Ovo je osnovna ideja projekta, koja ce se mozda menjati prilikom izrade. 
Projekat je zajednicki za ovaj predmet i SIAP.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Sviđa mi se ideja da analizirate i tvitove za neku short-term predikciju. Možete skrejpovati i izvore vesti poput ThomsonReuters-a, Guardian-a i slično, pa iskoristiti engine za tvitove i na tim izvorima, pa analizirati uticaj na cenu kriptovaluta.
