### ISSUE TITLE
Klasifikacija emocija u govoru

### ISSUE THREAD

**Issue by darionathor** [ftn-ai-lab/nm-2017#2]
Saša Lalić E2/102-2017

Određivanje emocija u glasu koristeći konvolucionu neuronsku mrežu. 
Audio zapisi se konvertuju u spektrograme, koje onda konvoluciona mreza obradjuje kao slike.
Problem odredjenje velicine ulaza je resen razbijanjem audio zapise na odredjenje duzine, i padovanje nulama podataka koji su isuvise mali.

[IEMOCAP](http://sail.usc.edu/iemocap/index.html) kao dataset.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Dopunite prijavu i napišite na koji način koristite konvolutivnu neuronsku mrežu za ovaj problem? Kako modelujete vremenske sekvence unutar audio zapisa i da li to radite?

**Comment by darionathor** [comment]
Github repo: https://github.com/darionathor/EmotionClassifier
