### ISSUE TITLE
Prepoznavanje rukom crtanih objekata

### ISSUE THREAD

**Issue by stkeky** [ftn-ai-lab/nm-2017#3]
## Članovi tima
- **R1 4/2017** Dragutin Marjanović
- **R1 5/2017** Stefan Ristanović

## Tema
Prepoznavanje pojmova sa crteža korisnika analizom velikog skupa crteža drugih objekata iz različitih kategorija. Osnovni cilj je rukom crtani objekat svrstati u neku od poznatih kategorija, upotrebom znanja stečenog klasifikacijom crteža korišćenjem veštačkih neuronskih mreža.

## Skup podataka
U sklopu ovog projekta koristiće se skup podataka dostupan na osnovu _Google_-ovog [Quick, Draw!](https://console.cloud.google.com/storage/browser/quickdraw_dataset/full?pli=1) projekta.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Ukoliko koristite običnu CNN koju obučavate nad skupom crteža objekata, a onda vršite klasifikaciju drugih objekata nad istim skupom klasa, projekat je za maksimalnu ocenu 8. Obratite pažnju na pretprocesiranje podataka i optimizaciju hiperparametara mreže, pa i tome posvetite deo u radu za maksimalnu ocenu.
