### ISSUE TITLE
Upravljanje filmom

### ISSUE THREAD

**Issue by svetozarstojkovic** [ftn-ai-lab/nm-2017#4]
## Tema
Tema projekta je da se obuci neuronska mreža koja će moći:
- da iz crno-belog videa kreira obojen video.
- da iz oštećenog videa kreira ispravan video.

## Opis projekta
Na ulaz se moze dovesti jedna od dve stvari:
1. Frejm provucen kroz filter rgb2gray;
2. Frejm na kom se nalaze šumovi;

Na izlaz će se dovesti nepromenjen frejm iz filma.

Koristiće se **Generative adversarial network (GAN)**.

## Dataset
Za dataset će se koristiti neki film koji ima veoma visok kvalitet.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

**Comment by svetozarstojkovic** [comment]
Github repo: https://github.com/svetozarstojkovic/video-processing

[Video processing using autoencoders.pdf](https://github.com/ftn-ai-lab/nm-2017/files/1826446/Video.processing.using.autoencoders.pdf)
