### ISSUE TITLE
Flappy Bird bot

### ISSUE THREAD

**Issue by bojanbla** [ftn-ai-lab/nm-2017#5]
## Članovi tima
- **R1 6/2017** &nbsp;&nbsp;Bojan Blagojević
- **R1 12/2017** Aleksandar Novaković

## Tema
   Implementacija autonomnog igrača(_bot_-a) za igru **Flappy Bird**. Rješenje će biti zasnovano na principima **reinforcement learning**-a. Koristiće se **Deep Q-Network** algoritam baziran na **konvolutivnoj neuronskoj mreži**.

## Podaci
   Podaci će biti generisani korištenjem nekog od **pygames** emulatora za Flappy Bird igru. Ulaz u pomenutu neuronsku mrežu će biti pikseli iz generisanih frejmova igrice.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.
