### ISSUE TITLE
Yoda chatbot

### ISSUE THREAD

**Issue by markozuzic** [ftn-ai-lab/nm-2017#6]
Marko Žužić E2-86/2017

**1. Definicija problema**
Izrada sistema za dijalog između računara i čoveka (engl. _chatbot_). Chatbot će davati odgovor transformisan po jezičkom modelu fiktivnog karaktera Jode iz Star Wars serijala. 

**2. Skup podataka**
U projektu će biti korišćen _Cornell Movie Dialog Corpus_ dataset, koji sadrži kolekciju razgovora izvučenih iz filmova. 
Odgovori u dijalogu će biti transformisani u željeni model govora upotrebom Stanford-ove CoreNLP biblioteke.

**3. Metodologija**
Neuronska mreža će biti obučena da generiše tekst po zadatom jezičkom modulu, upotrebom seq2seq modela.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.

Da li prvo generišete odgovor na pitanje, pa ga onda transformišete u stil Jode, ili odmah odgovarate kao Joda. U oba slučaja je dataset potencijalni problem.

Nadam se da ćete biti u mogućnosti da iz Cornell dataseta izdvojite sve delove teksta koji su vezani za Jodu i da ćete imati dovoljno dobar dataset za chatbot, pošto je Cornel mnogo širi i u sebi ima mnogo drugih stvari. Iz ove perspektive mi to deluje diskutabilno, ali se nadam da ste dobro istražili sam pristup i sam skup podataka i da tačno znate šta se u njemu nalazi i da to možete koristiti.

**Comment by AndrijanaStefanovic** [comment]
Odmah odgovaramo kao Joda.

Razmatramo i druge mogućnosti za dataset(možda i da spojimo pogodne delove iz više njih), videćemo kako će se razdvijati transformacija u pogodan oblik.

**Comment by markozuzic** [comment]
Odmah odgovaramo kao Joda.

Razmatramo i druge mogućnosti za dataset(možda i da spojimo pogodne delove iz više njih), videćemo kako će se razdvijati transformacija u pogodan oblik.
