### ISSUE TITLE
Čitanje sa usana

### ISSUE THREAD

**Issue by milicanikolic** [ftn-ai-lab/nm-2017#7]
Tim: Sarvan Nebojša E2 59/2017
        Manojlović Nina E2 53/2017
        Nikolić Milica E2 48/2017

Cilj projekta je ispisati reči pročitane sa usana. Za treniranje koristiće se skup video snimaka, bez zvuka. Trenutno, razmatramo skup [MIRACL-VC1](https://sites.google.com/site/achrafbenhamadou/-datasets/miracl-vc1). Postoji više mogućih skupova video snimaka, ali zbog nedostajućih transkripata nismo sigurni da li će biti od koristi. Na mogućnost pristupa još jednom relevantnom skupu još uvek čekamo odgovor. Ukoliko se odlučimo za prepoznavanje reči na srpskom jeziku, dataset će se najverovatnije praviti ručno, s obzirom na to da nismo naišli na skup sa ovakvim podacima. Za detekciju lica sa video snimaka biće iskorišćen neki od postojećih softvera. Plan je da se iskoristi pretrenirana konvolutivna mreža u kombinaciji sa LSTM-om.

**Comment by ivan7792** [comment]
Tema odobrena, srecan rad.
