### ISSUE TITLE
Prepoznavanje tehničke opremljenosti nekretnine na osnovu slike iz oglasa

### ISSUE THREAD

**Issue by MladenVidovic** [ftn-ai-lab/nm-2017#8]
## Tim
- Ivan Radosavljević R1-13/2017
- Aleksandra Mitrović R1-14/2017
- Mladen Vidović R1-15/2017

## Tema
Prepoznavanje kućnih uređaja (klima uređaj, veš mašina...) na slici. Ovo se radi za prepoznavanje tehničke opremljenosti nekretnine na osnovu slike iz oglasa radi verifikacije podataka ostavljenih u oglasu (projekat uvezan sa SIAP projektom). 

## Podaci
Skup podataka čine slike iz otprilike 100 000 oglasa scrape-ovanih sa stranice [nekretnine.rs](https://www.nekretnine.rs/). 

## Metodologija
Za prepoznavanje će biti upotrebljena pretrenirana konvolutivna neuronska mreža, obučena na [COCO](http://cocodataset.org/#home) skupu podataka.

**Comment by ivan7792** [comment]
Tema odobrena, srećan rad.
